### PR TITLE
Assignmetn5-Hadi-Cynthia

### PR DESCRIPTION
**Pull request by HadiM2**
@HadiM2
@montalcy

Site Link: [🥇](https://gentle-sand-0aaa3be10.5.azurestaticapps.net/)

you need to log in to to access the editWords, You are able to log in with any username and password. You just can't have it empty when clicking sign in. 

Only login with these credentials is able to delete and add words:
admin@masterOfUniverse.com
1234

### CODE REVIEW

**Comment by SergeiAshikhmin** [comment]
I will review this :)

**Review by SergeiAshikhmin — COMMENTED** [review]
Good job 👍 
I assume you are not done yet. Great start overall, good luck guys.

Create an editor for the available words ✅
Create a page named "WordEditor" that allows words to be edited ✅
Support deleting a word ❌
- I wasn't able to locate the delete button

Support adding a new word ❌
- This feature is not working. When debugging, the newWord value is empty string. It is not getting value from text-filed for some reason.

Editing words is not supported ✅
Duplicate words should not be allowed ✅
Add & support changing the common word boolean flag ❌
- Also didn't find a way to change isCommon flag

Filter the list of returned words by common words ❌
- The list contains both common and not common words. I assume the filter is not working yet.

Words should be sorted alphabetically ✅
Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅
Provide a menu item for navigating to the WordEditor page ✅
Anyone can look at the word list ✅
Word list is paginated on the server side (10-100 per page) ❌
- Word list is paginated but not on the server side. 

Any logged in user can change the common word flag ❌
- I wasn't able to locate any log in features

There is a login page/component/popup/etc for users to sign in ❌
Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ❌
Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ❌

**Comment by rahat15** [comment]
Good work


Create an editor for the available words ✅
Create a page named "WordEditor" that allows words to be edited ✅
Support deleting a word ❌

Support adding a new word ❌

Editing words is not supported ✅
Duplicate words should not be allowed ✅
Add & support changing the common word boolean flag ❌

Filter the list of returned words by common words ❌

Words should be sorted alphabetically ✅
Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅
Provide a menu item for navigating to the WordEditor page ✅
Anyone can look at the word list ✅
Word list is paginated on the server side (10-100 per page) ❌

Any logged in user can change the common word flag ❌

There is a login page/component/popup/etc for users to sign in ❌
Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ❌
Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ❌

**Comment by montalcy** [comment]
> Good work
> 
> Create an editor for the available words ✅ Create a page named "WordEditor" that allows words to be edited ✅ Support deleting a word ❌
> 
> Support adding a new word ❌
> 
> Editing words is not supported ✅ Duplicate words should not be allowed ✅ Add & support changing the common word boolean flag ❌
> 
> Filter the list of returned words by common words ❌
> 
> Words should be sorted alphabetically ✅ Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅ Provide a menu item for navigating to the WordEditor page ✅ Anyone can look at the word list ✅ Word list is paginated on the server side (10-100 per page) ❌
> 
> Any logged in user can change the common word flag ❌
> 
> There is a login page/component/popup/etc for users to sign in ❌ Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ❌ Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ❌

Thanks Rahat! We added adding and deleting a word, just making the claims

**Comment by montalcy** [comment]
> Good job 👍 I assume you are not done yet. Great start overall, good luck guys.
> 
> Create an editor for the available words ✅ Create a page named "WordEditor" that allows words to be edited ✅ Support deleting a word ❌
> 
> * I wasn't able to locate the delete button
> 
> Support adding a new word ❌
> 
> * This feature is not working. When debugging, the newWord value is empty string. It is not getting value from text-filed for some reason.
> 
> Editing words is not supported ✅ Duplicate words should not be allowed ✅ Add & support changing the common word boolean flag ❌
> 
> * Also didn't find a way to change isCommon flag
> 
> Filter the list of returned words by common words ❌
> 
> * The list contains both common and not common words. I assume the filter is not working yet.
> 
> Words should be sorted alphabetically ✅ Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅ Provide a menu item for navigating to the WordEditor page ✅ Anyone can look at the word list ✅ Word list is paginated on the server side (10-100 per page) ❌
> 
> * Word list is paginated but not on the server side.
> 
> Any logged in user can change the common word flag ❌
> 
> * I wasn't able to locate any log in features
> 
> There is a login page/component/popup/etc for users to sign in ❌ Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ❌ Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ❌

Thanks Sergei! We got adding and deleting a word, just making the claims.. let us know if you have any more suggestions !

**Comment by MikaellaCroskrey-IntelliTect** [comment]
## Assignment 5


### Create an editor for the available words ✅
  - Create a page named "WordEditor" that allows words to be edited ✅
    - Support deleting a word ✅ Half credit - should be implemented in CRUD
    - Support adding a new word ✅ Half credit - should be implemented in CRUD
    - Editing words is not supported ✅ 
    - Duplicate words should not be allowed ✅
    - Add & support changing the common word boolean flag ✅ Half credit - should be implemented in CRUD
      - Filter the list of returned words by common words ❌ No filtering found in UI.
    - Words should be sorted alphabetically ✅
  - Provide a text box for searching words AS YOU TYPE which supports searching for words starting with letters specified ✅
  - Provide a menu item for navigating to the WordEditor page ✅
    - Anyone can look at the word list ✅
    - Word list is paginated on the server side (10-100 per page) ✅
  - Any logged in user can change the common word flag ✅
    - There is a login page/component/popup/etc for users to sign in ✅
  - Only users over 21 years of age (based on birthday) with a claim of MasterOfTheUniverse can add and remove words ✅ Half credit - Authorization is only being done on the client side
  - Users can be set up at start up in the API project as a seed (apriori), there does not need to be a sign up mechanism ✅ Claims don't appear to be added to the seeded roles


## Extra Credit
Find a bug in the application, create an issue, submit a pull request against the issue ❌
Add the ability to sign up for an account by inputting an email and password ❌ Attempted but not finished?
Allow the user to elevate their level of privelage by inputting a secret phrase ❌
Select pagination record count ✅

Code looks decent overall that being said, part of the purpose for this assignment was to implement a CRUD interface and use the appropriate auth on the server side.

**Pull request closed without merging**
